# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='votable_song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('song_title', models.TextField()),
                ('song_artist', models.TextField()),
                ('song_album', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='vote_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_count', models.IntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votable_song')),
            ],
        ),
    ]
