# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_options', models.ManyToManyField(to='vote.vote_option')),
            ],
        ),
    ]
