# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='suspended_song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('song_title', models.TextField()),
                ('song_artist', models.TextField()),
                ('song_album', models.TextField()),
            ],
        ),
    ]
