# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_suspended_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspended_song',
            name='s_order',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 9, 20, 42, 41, 384702, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
