# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_suspended_song_s_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='votable_song',
            name='r_num',
            field=models.IntegerField(default=0),
        ),
    ]
