# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_remove_votable_song_r_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='v_stamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 11, 9, 44, 25, 90896, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
