# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_vote_v_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_options',
        ),
        migrations.DeleteModel(
            name='vote',
        ),
    ]
