# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20171011_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votable_song',
            name='song_album',
            field=models.TextField(default='missing-album'),
        ),
        migrations.AlterField(
            model_name='votable_song',
            name='song_artist',
            field=models.TextField(default='missing-artist'),
        ),
        migrations.AlterField(
            model_name='votable_song',
            name='song_title',
            field=models.TextField(default='missing-title'),
        ),
    ]
