# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20171011_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_option',
            name='song',
        ),
        migrations.AddField(
            model_name='vote_option',
            name='file_name',
            field=models.TextField(default='/'),
        ),
        migrations.AddField(
            model_name='vote_option',
            name='song_artist',
            field=models.TextField(default='d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote_option',
            name='song_title',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
