# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_auto_20171011_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote_option',
            name='file_name',
            field=models.TextField(),
        ),
    ]
